### ISSUE TITLE
Export default function gebruiken

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#1]
Je exporteert maar 1 functie, dus zou je die veel simpeler kunnen exporteren door

```js
export default function() {/*...*/}

// OF

export default () => {/*...*/}
```

te gebruiken

https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/modules/helperFunctions.js#L1-L3

**Comment by WesselSmit** [comment]
Dit zou kunnen als ik maar 1 functie ga exporteren, maar ik ben van plan om in de toekomst meer functies aan deze module toe te voegen
