### ISSUE TITLE
Beter alle selectors opslaan in variabelen

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#10]
Niet alleen voor leesbaarheid maar ook performance dingetje. Als je overal `document.getElementById('henk').addEventListener()` etc. gebruikt moet JavaScript constant een lookup doen naar de DOM welk element het over gaat.

**Comment by Razpudding** [comment]
Yes, en onthoud: De verwijzing naar het html element hoeft niet geupdate te worden maar de waarde van bijv de inhoud van dat element kan veranderen en moet je dus wel elke keer opnieuw ophalen.
