### ISSUE TITLE
module names

### ISSUE THREAD

**Issue by devsjors** [WesselSmit/web-app-from-scratch-1920#12]
helperFunctions.js might not be a good name because a module executes or returns a specific thing. So I would call this module to what it does and create a module for every specific function(s)

**Comment by Razpudding** [comment]
I generally agree although sometimes it's useful to have a module like 'utilities' which has a bunch of useful functions. If you get a couple of those functions that belong together (like some string functions for capitalizing letters in words) that would be a good time to place them in their own "string alterations" module.

**Comment by WesselSmit** [comment]
I agree with Razpudding on the "putting small functions in an utilities module, untill there are enough related utilities to form a new module". In the refactored code I called the module "utilities" instead of "helperFunctions" as I think it's more descriptive. Thanks for the feedback!
