### ISSUE TITLE
Awesome functionalities

### ISSUE THREAD

**Issue by devsjors** [WesselSmit/web-app-from-scratch-1920#14]
Super awesome that the user can pick their options for the Trivia Cards.
https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/script.js#L5-L10

Very good flow of the user interface. All the screens follow up each other in a logical way. Routing would make this game awesome!

**Comment by WesselSmit** [comment]
thanks a lot
