### ISSUE TITLE
Comments toevoegen voor duidelijkheid

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#2]
Wellicht dat deze code te complex is opgebouwd. Ik snap namelijk niet wat je hier probeert te doen, behalve dat je een array probeert te randomizen op de één of andere manier. 

Een comment erboven met wat deze functie precies doet zou het een stuk duidelijker maken, ook voor jezelf als je later terug kijkt.

https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/modules/helperFunctions.js#L5-L13

**Comment by WesselSmit** [comment]
Since I have 2 issues both about adding comments I'm closing this one.
