### ISSUE TITLE
Find an alternative for innerHTML

### ISSUE THREAD

**Issue by Razpudding** [WesselSmit/web-app-from-scratch-1920#20]
Look up the dangers and consider using an alternative method.

**Comment by WesselSmit** [comment]
I know the dangers of innerHTML but I don't think there is a safe alternative. 

The JSON result is a string with HTML-code characters in it, so it has to be parsed to be human readable text.

I plan on using insertAdjecentHTML but that of course still has the same dangers.

**Comment by Razpudding** [comment]
https://stackoverflow.com/questions/7476638/if-people-recommend-i-shouldnt-use-innerhtml-what-then-should-i-instead-use

Op zo 9 feb. 2020 om 21:38 schreef WesselSmit <notifications@github.com>:

**Comment by WesselSmit** [comment]
closing tread because of concept switch and this not being a problem anymore since the API data doesn't include unicode/ASCII characters.
