### ISSUE TITLE
Give credit for used code within the code file itself

### ISSUE THREAD

**Issue by Razpudding** [WesselSmit/web-app-from-scratch-1920#21]
You mention at the bottom of your readme the randomizer code isn't yours. You should also do it [within the code file](https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/modules/helperFunctions.js#L5) right above the code you used including the source.

**Comment by WesselSmit** [comment]
credits are now both in readme & code
