### ISSUE TITLE
Interaction Diagram

### ISSUE THREAD

**Issue by RooyyDoe** [WesselSmit/web-app-from-scratch-1920#24]
- Je kan de "Page-Load" toevoegen aan de diagram, zodat je weet waar je app begint.

- Je gaat twee keer in het begin bij "App" naar "Utils". Snap niet waarom dit gebeurd? volgens mij kan je een van de twee weghalen. Daarnaast kan je misschien ook laten zien wat er gebeurd als je bijvoorbeeld filtert? ( Nieuwe API call? functie? )

- Naast deze twee punten is de interaction diagram duidelijk!

**Comment by WesselSmit** [comment]
added page load
