### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by RooyyDoe** [WesselSmit/web-app-from-scratch-1920#25]
Ben benieuwd wat je uiteindelijk gaat doen met de overview pagina?

Word het een soort van Instagram layout? of ga je puur de afbeeldingen laten zien? 

In je diagrammen heb je het ook over filter en sorteren? Op welke data ga je dit uitvoeren uiteindelijk?

LocalStorage is amazing af!

**Comment by WesselSmit** [comment]
Overview page will be just images, detail page will contain additional metadata/info

>LocalStorage is amazinf af!
Thanks :)
