### ISSUE TITLE
Gebruik een template literal voor string concatenation

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#3]
Onderstaande ziet er aardig rommelig uit, dit zou je kunnen oplossen door de boel op te breken, na elke plus op een nieuwe lijn te beginnen of template literals te gebruiken waardoor je dus iets als het volgende krijgt:

```js
const story = `The horse has ${nthOfLegs} legs and eats ${nthOfFood} every day`
```

https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/modules/getData.js#L2-L3

**Comment by kriskuiper** [comment]
Wat ik me ook net bedenk is dat je die limit, type en difficulty uit het triviaSettings object kan destructuren:

```js
const { limit, difficulty, etc } = triviaSettings
```

Dan kan je in je url 't volgende doen:

```js
const baseUrl = `https://opentdb.com/api.php`

const url = `${baseUrl}?amount=${limit}&category=${category}&difficulty=${difficulty}&type=${type}`
```

**Comment by WesselSmit** [comment]
Due to concept switch this isn't relevant anymore.
