### ISSUE TITLE
Rubric

### ISSUE THREAD

**Issue by damianveltkamp** [WesselSmit/web-app-from-scratch-1920#30]
- App structuur en code kwaliteit
Voldoende
Wordt geen gebruik gemaakt van global scope variablen, echter zijn nog niet alle modules uitgewerkt zoals aangegeven in je actor diagram. Dit heb je zelf al geconstateerd en genoteerd in je todo's.

- Data ophalen, manipuleren en tonen
Onvoldoende
Er wordt met een promise data opgehaald uit de NASA api. De data die opgehaald is word niet opgeschoond, echter is dat in dit geval niet nodig omdat het enkel om een foto met tekst gaat en er geen onnodige date geserveerd wordt. Er is nog geen gebruik gemaakt van een virtualdom of template engine.

- States en routes afhandelen
Onvoldoende
Er wordt aan de hand van een hash router data getoond, de volledige implementatie is nog niet daar maar er wordt aan gewerkt. Het interaction diagram is nog niet helemaal duidelijk waar het begint en eindigt, echter zijn wel alle modules en acties aanwezig maar dit moet op een meer logische manier gestructureerd worden. Er is nog niks gedaan aan feedback omdat het concept omgegooid is deze week en er nog geen feedback ronde is geweest.

**Comment by WesselSmit** [comment]
* Data ophalen, manipuleren en tonen
ook moeten de data-manipulatie functies ook nog hierin verwerkt worden (map, filter, reduce)

**Comment by WesselSmit** [comment]
* app structure
**good enough**
no global variables, good use of modules 

* data fetching & manipulation
**good enough**
data is cleaned & filtered, I've setup a custom function that uses a template engine to create HTML

* states and routes
**idk**
hash-routing is done.

**Comment by WesselSmit** [comment]
TODOs to cpmplete the rubric:
* use the `reduce` method
* update actor diagram (feedback)
* update interaction diagram (feedback, github issues)
