### ISSUE TITLE
Moet dit een number zijn?

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#8]
Volgens mij, gekeken naar andere logica, wordt de limit etc. toegevoegd aan de url? Kan het fout hebben hoor, maar dan hoeft het volgens mij geen number type te zijn omdat het toch aan een string wordt toegevoegd (de url).

Daarnaast zou ik iets explicieter zijn als je iets omzet naar een andere type, je gebruikt nu `+someVariable`, ik zou dit doen met `Number(someVariable)`. Anyway, je snapt wat ik te zeuren heb.

https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/script.js#L14-L15

**Comment by Razpudding** [comment]
Mee eens. Eigenlijk zou je eerst willen checken of een gebruiker wel een getal in heeft gevuld (en als dat niet zo is er een bericht over weergeven). Dat kan gechecked worden als de gebruiker naar het volgende veld gaat of wanneer er op de start knop wordt geklikt.
Als het een getal is dan wordt die als string toegevoegd aan de url.

**Comment by WesselSmit** [comment]
Due to concept switch this isn't relevant anymore.
