### ISSUE TITLE
Ik zou document.getElementById gebruiken

### ISSUE THREAD

**Issue by kriskuiper** [WesselSmit/web-app-from-scratch-1920#9]
```js
document.getElementById('button-thing') // is veel simpeler te lezen in je js
```

https://github.com/WesselSmit/web-app-from-scratch-1920/blob/d61345ac7038447e1756f0b9416fa9f96f4d3ede/script.js#L52

**Comment by Razpudding** [comment]
En minder fout gevoelig! Als je een nieuwe button toevoegt aan de pagina kan de huidige logica breken.
